name: config sonar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Create or verify SonarQube Quality Gate
        run: |
          GATE_NAME=$REPO_NAME

          QUALITY_GATE=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/list?organization=$SONAR_ORGANIZATION" | jq -r --arg gate_name "$GATE_NAME" '.qualitygates[] | select(.name == $gate_name)')
          GATE_ID=$(echo "$QUALITY_GATE" | jq -r '.id')
          echo "::debug::Quality Gate ID: $GATE_ID and info: $QUALITY_GATE"

          EXIST_GATE=$(echo "$QUALITY_GATE" | jq -r '.name')
          if [ -z "$EXIST_GATE" ]; then
            echo "The quality gate '$GATE_NAME' does not exist. Creating..."
 
            GATE_INFO=$(curl -s -u $SONAR_TOKEN: -X POST \
              "$SONAR_HOST_URL/api/qualitygates/create" \
              -d "name=$GATE_NAME" \
              -d "organization=$SONAR_ORGANIZATION")
            GATE_ID=$(echo "$GATE_INFO" | jq -r '.id')
              
            echo "::debug::Created Quality Gate ID: $GATE_ID and info: $GATE_INFO"
          else
            echo "The quality gate '$GATE_NAME' already exists. Skipping creation."
          fi

      - name: Set conditions for the Quality Gate
        run: |
            ls .github
            GATE_CONDITIONS=$(cat .github/conditions-quality-gate.json | jq -r '.conditions')
            echo "Conditions to set: ${GATE_CONDITIONS[0]}"
            echo "Conditions: ${GATE_CONDITIONS[1]}"
            # curl -s -u $SONAR_TOKEN: -X POST \
            # "$SONAR_HOST_URL/api/qualitygates/create_condition" \
            # -d "gateId=$GATE_ID" \
            # -d "organization=$SONAR_ORGANIZATION" \
            # -d "metric=coverage" \
            # -d "op=LT" \
            # -d "error=90"

      - name: debug
        run: |
            echo "REPO_NAME: $REPO_NAME"
    
    #   # 1. PROVISION: Verificar si existe o crear el proyecto
    #   - name: Ensure SonarQube Project Exists
    #     run: |
    #       PROJECT_KEY="mi-proyecto-amate"
    #       PROJECT_NAME="$REPO_NAME"
          
    #       # Intentamos buscar el proyecto
    #       STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -u ${{ secrets.SONAR_TOKEN }}: \
    #         "${{ secrets.SONAR_HOST_URL }}/api/projects/search?projects=$PROJECT_KEY")
          
    #       if [ "$STATUS_CODE" -ne 200 ]; then
    #         echo "Proyecto no encontrado, creando..."
    #         curl -u ${{ secrets.SONAR_TOKEN }}: -X POST \
    #           "${{ secrets.SONAR_HOST_URL }}/api/projects/create" \
    #           -d "name=$PROJECT_NAME" \
    #           -d "project=$PROJECT_KEY"

    #         curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
    #           "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/select" \
    #           -d "gateName=$GATE_NAME" \
    #           -d "projectKey=mi-proyecto-amate"
    #       else
    #         echo "El proyecto ya existe en SonarQube."
    #       fi

    #   # 2. ANALYSIS: Ejecutar el scanner
    #   - name: SonarQube Scan
    #     uses: sonarsource/sonarqube-scan-action@master
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     with:
    #       args: >
    #         -Dsonar.projectKey=mi-proyecto-amate
    #         -Dsonar.sources=.
    #         -Dsonar.verbose=true

    #   # 3. QUALITY GATE: Esperar el resultado
    #   - name: SonarQube Quality Gate check
    #     id: sonarqube-quality-gate-check
    #     uses: sonarsource/sonarqube-quality-gate-action@master
    #     timeout-minutes: 5
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
