name: config sonar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Get Repository name
        id: get_repo_name
        run: |
            FULL_REPO=${GITHUB_REPOSITORY}
            REPO=${FULL_REPO#*/}
            echo "REPO_NAME=$REPO" >> $GITHUB_ENV



      - name: Set Quality Gate
        run: |
          GATE_NAME=$REPO_NAME
          SONAR_ORGANIZATION="${{ secrets.SONAR_ORGANIZATION }}"
          GATE_ID="" # Variable para almacenar el ID del Gate (si es necesario)

          # Verificar si el Quality Gate ya existe
          # 1. Obtenemos toda la lista en una variable
          LISTA_GATES=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/list?organization=$SONAR_ORGANIZATION" | jq -r '.qualitygates[] | select(.organization == "'$SONAR_ORGANIZATION'") | .name')
          
          echo "lista de gates: $LISTA_GATES"
          # 2. Buscamos el nombre dentro de la variable (esto no rompe el script)
          if [[ "$LISTA_GATES" == *"$GATE_NAME"* ]]; then
            echo "El Gate ya existe."
            GATE_EXISTS="1"
          else
            echo "El Gate no existe."
            GATE_EXISTS="0"
          fi
          echo "Configuring Quality Gate: $GATE_EXISTS"

          if [ "$GATE_EXISTS" -eq 0 ]; then
            echo "El Quality Gate '$GATE_NAME' no existe. Creándolo..."
            
            # Crear el Gate
            GATE_INFO=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/create" \
              -d "name=$GATE_NAME" \
              -d "organization=$SONAR_ORGANIZATION")
              
            echo "Quality Gate '$GATE_NAME' creado con éxito."
          else
            echo "El Quality Gate '$GATE_NAME' ya existe. Saltando creación."
          fi

        #    # Añadir condiciones (90% coverage y 5% duplicación)
        #     curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
        #       "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/create_condition" \
        #       -d "gateName=$GATE_NAME" \
        #       -d "organization=$SONAR_ORGANIZATION" \
        #       -d "metric=coverage" \
        #       -d "op=LT" \
        #       -d "error=90"
              
        #     curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
        #       "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/create_condition" \
        #       -d "gateName=$GATE_NAME" \
        #       -d "organization=$SONAR_ORGANIZATION" \
        #       -d "metric=duplicated_lines_density" \
        #       -d "op=GT" \
        #       -d "error=5"

      - name: debug
        run: |
            echo "REPO_NAME: $REPO_NAME"
    
    #   # 1. PROVISION: Verificar si existe o crear el proyecto
    #   - name: Ensure SonarQube Project Exists
    #     run: |
    #       PROJECT_KEY="mi-proyecto-amate"
    #       PROJECT_NAME="$REPO_NAME"
          
    #       # Intentamos buscar el proyecto
    #       STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -u ${{ secrets.SONAR_TOKEN }}: \
    #         "${{ secrets.SONAR_HOST_URL }}/api/projects/search?projects=$PROJECT_KEY")
          
    #       if [ "$STATUS_CODE" -ne 200 ]; then
    #         echo "Proyecto no encontrado, creando..."
    #         curl -u ${{ secrets.SONAR_TOKEN }}: -X POST \
    #           "${{ secrets.SONAR_HOST_URL }}/api/projects/create" \
    #           -d "name=$PROJECT_NAME" \
    #           -d "project=$PROJECT_KEY"

    #         curl -s -u ${{ secrets.SONAR_TOKEN }}: -X POST \
    #           "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/select" \
    #           -d "gateName=$GATE_NAME" \
    #           -d "projectKey=mi-proyecto-amate"
    #       else
    #         echo "El proyecto ya existe en SonarQube."
    #       fi

    #   # 2. ANALYSIS: Ejecutar el scanner
    #   - name: SonarQube Scan
    #     uses: sonarsource/sonarqube-scan-action@master
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     with:
    #       args: >
    #         -Dsonar.projectKey=mi-proyecto-amate
    #         -Dsonar.sources=.
    #         -Dsonar.verbose=true

    #   # 3. QUALITY GATE: Esperar el resultado
    #   - name: SonarQube Quality Gate check
    #     id: sonarqube-quality-gate-check
    #     uses: sonarsource/sonarqube-quality-gate-action@master
    #     timeout-minutes: 5
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
